export const enum LangOperatorType {
  
    ADDITION = "ADDITION",
    SUBTRACTION = "SUBTRACTION",
    MULTIPLICATION = "MULTIPLICATION",
    DIVISION = "DIVISION",
    MODULO = "MODULO",

    EQUALS = "EQUALS",
    NOT_EQUALS = "NOT_EQUALS",
    GREATER_THAN = "GREATER_THAN",
    LESS_THAN = "LESS_THAN",
    GREATER_OR_EQUAL = "GREATER_OR_EQUAL",
    LESS_OR_EQUAL = "LESS_OR_EQUAL",

    AND = "AND",
    OR = "OR",
    NOT = "NOT",

    ASSIGN = "ASSIGN",
    ADD_ASSIGN = "ADD_ASSIGN",
    SUB_ASSIGN = "SUB_ASSIGN",
    MUL_ASSIGN = "MUL_ASSIGN",
    DIV_ASSIGN = "DIV_ASSIGN",
    MOD_ASSIGN = "MOD_ASSIGN",

    BITWISE_AND = "BITWISE_AND",
    BITWISE_OR = "BITWISE_OR",
    BITWISE_XOR = "BITWISE_XOR",
    BITWISE_NOT = "BITWISE_NOT",
    SHIFT_LEFT = "SHIFT_LEFT",
    SHIFT_RIGHT = "SHIFT_RIGHT",

    TERNARY = "TERNARY",
    NULLISH_COALESCING = "NULLISH_COALESCING",

    OPTIONAL_CHAINING = "OPTIONAL_CHAINING",
}