export const enum LangKeywordType {
    CONTROL_FLOW = "CONTROL_FLOW",
   
    CONSTANT_DECLARATION = "CONSTANT_DECLARATION",

    VARIABLE_DECLARATION = "VARIABLE_DECLARATION",
    
    FUNCTION_DECLARATION = "FUNCTION_DECLARATION",
    FUNCTION_IDENTIFIER = "FUNCTION_IDENTIFIER",
    FUNCTION_PARAMETER = "FUNCTION_PARAMETER"
}
